name: 'build-test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Dependencies Node Install
        run: npm install

      - name: Run Test
        run: |
          npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Dependencies Node Install
        run: npm install

      - name: Run Linter
        run: npm run lint
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
